name: Build

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Install dependencies
      run: npm i

    - name: Build everything
      run: npm run build

    - name: Push update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        commit_message: "[AUTO] Update icon set"

