name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Try @mdi/js update
      run: npm install @mdi/js

    - name: Build Vue components
      run: npm run build
