name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Install dependencies
      run: npm i

    - name: Build Vue components
      run: npm run build

    - name: Get package version
      uses: martinbeentjes/npm-get-version-action@master
      id: version
      with:
        path: dist
