name: Publish to NPM

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install current dependencies
        run: npm install
        
      - name: Check for @mdi/js update
        run: npm install @mdi/js
        
      - name: Commit updated @mdi/js version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO] Update mdi/js version"

      - name: Publish to NPM
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          npm run build
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
